export const projects = [
  {
    slug: 'withsubtitles',
    name: 'WithSubtitles',
    label: 'Give your videos a voice.',
    category: 'Video & captions',
    description: 'Automatic captions for short-form videos. WithSubtitles helps put your words on screen, so your story can be understood with or without sound.',
    url: 'https://withsubtitles.com',
    domain: 'withsubtitles.com',
    theme: 'subtitles',
    mark: 'subtitles',
  },
  {
    slug: 'withconverter',
    name: 'WithConverter',
    label: 'A little change of format.',
    category: 'File conversion',
    description: 'A small project exploring a simpler way to convert files. Less friction between the file you have and the format you need.',
    url: 'https://withconverter.com',
    domain: 'withconverter.com',
    theme: 'converter',
    mark: 'converter',
  },
  {
    slug: 'whatthefreefont',
    name: 'whatthefreefont.com',
    label: 'Just your type.',
    category: 'Typography',
    description: 'A project for the love of typography and free fonts. A little space to explore letterforms and find a new direction for your next design.',
    url: 'https://whatthefreefont.com',
    domain: 'whatthefreefont.com',
    theme: 'fonts',
    mark: 'fonts',
  },
]
